models:

  # given with respect to static platform
  cube1_static: [
      0, 0, 1, 0.0625,
      0, -1, 0, 0.0625,
      1, 0, 0, 0,
      0, 0, 0, 1
    ]
  cube2_static: [
      1, 0, 0, -0.0625,
      0, -1, 0, 0.0625,
      0, 0, -1, 0,
      0, 0, 0, 1
    ]
  cube3_static: [
      1, 0, 0, 0.0625,
      0, 0, 1, -0.0625,
      0, -1, 0, 0,
      0, 0, 0, 1
    ]
  cube4_static: [
      0, -1, 0, -0.0625,
      -1, 0, 0, -0.0625,
      0, 0, 1, 0,
      0, 0, 0, 1
    ]

  # given with respect to dynamic turntable
  cube9_dynamic: [
      1, 0, 0, 0.2163,
      0, 1, 0, 0,
      0, 0, 1, 0.025,
      0, 0, 0, 1
    ]
  cube10_dynamic: [
      0.70716, -0.70716, 0, 0.1529,
      0.70716, 0.70716, 0, 0.1529,
      0, 0, 1, 0.025,
      0, 0, 0, 1
    ]
  cube11_dynamic: [
      0, -1, 0, 0,
      1, 0, 0, 0.2163,
      0, 0, 1, 0.025,
      0, 0, 0, 1
    ]
  cube12_dynamic: [
      -0.70716, -0.70716, 0, -0.1529,
      0.70716, -0.70716, 0, 0.1529,
      0, 0, 1, 0.025,
      0, 0, 0, 1
    ]
  cube13_dynamic: [
     -1, 0, 0, -0.2163,
      0, -1, 0, 0,
      0, 0, 1, 0.025,
      0, 0, 0, 1
    ]
  cube14_dynamic: [
      -0.70716, 0.70716, 0, -0.1529,
      -0.70716, -0.70716, 0, -0.1529,
      0, 0, 1, 0.025,
      0, 0, 0, 1
    ]
  cube15_dynamic: [
      0, 1, 0, 0,
     -1, 0, 0, -0.2163,
      0, 0, 1, 0.025,
      0, 0, 0, 1
    ]
  cube16_dynamic: [
      0.70716, 0.70716, 0, 0.1529,
      -0.70716, 0.70716, 0, -0.1529,
      0, 0, 1, 0.025,
      0, 0, 0, 1
    ]

  # given with respect to robot base
  camera: [
      -1, 0, 0, 0,
      0, 1, 0,  0,
      0, 0, -1, 1.5,
      0, 0, 0, 1
    ]
  tag0: [
      1, 0, 0, -0.5,
      0, 1, 0, 0,
      0, 0, 1, 0,
      0, 0, 0, 1
    ]
